### PR TITLE
bug(flex): Fix responsiveStyle param

### LINKED ISSUE #17: Wrap prop on Flex component
First off, thanks for picking this repo up and maintaining it.

Just moved to from `grid-styled` to this repo, im running into a issue where the `wrap` prop on the `Flex`.  I refactored from `wrap` to `flexWrap` and it is not adding `flex-wrap` attribute in the css.

Just curious if you knew why?

### PR DESCRIPTION
**Pull request by bringking**
### How does this PR make you feel (in animated GIF format)?
sad

#### Prerequisites
- Is there any documentation that needs to be updated? **N/A**

#### Please provide a summary of changes and any background context...
The props passed to `responsiveStyles` for `flexWrap` were incorrect. The third param is the value to insert if the param is a boolean. This PR adds the 'wrap' value as the boolean value.

Closes #17 

---

### Technical Review
* [X] Is there enough test coverage?
* Ask questions, have a conversation!

#### How should this be manually tested (any data/API considerations)?
Checkout branch, make sure `flex-wrap` is being applied correctly when using the prop `flexWrap`

### CODE REVIEW

File: src/Flex.js [hunk 1]
```diff
@@ -5,7 +5,7 @@ import { oneOfType, number, string, array, bool } from "prop-types";
 import propTypes from "./propTypes";
 import Box from "./Box";
 
-const flexWrap = responsiveStyle("flex-wrap", "flex-wrap", "flexWrap");
+const flexWrap = responsiveStyle("flex-wrap", "flexWrap", "wrap");
```
Comment (theshortcut) [inline src/Flex.js]: 😬
